### PR TITLE
284 get rid of smaller dependencies

### PR DESCRIPTION
**Pull request by alessioC42**

### CODE REVIEW

**Comment by alessioC42** [comment]
This some kind of "Pre-PR" before my structural rewrite of the App to Support teacher accounts. Feel free to remove dependencies, that are easy to implement, but hurry. If you do not find the time do it after the rewrite.

**Review by kurwjan — APPROVED** [review]
I don't have time now for rewriting color_hash and this selecting thing in conversation so I'll approve it.

**Review by kurwjan — CHANGES_REQUESTED** [review]
When I try to download a pdf file in Mein Unterricht this happened:
```
I/flutter ( 5526): 2024-11-07 22:03:05 [ERROR] Lanis: type 'String' is not a subtype of type 'List<int>'
I/flutter ( 5526): Lanis
I/flutter ( 5526): #0      SPHclient.downloadFile (package:sph_plan/client/client.dart:447:34)
I/flutter ( 5526): <asynchronous suspension>
I/flutter ( 5526): #1      launchFile.<anonymous closure> (package:sph_plan/shared/launch_file.dart:24:43)
I/flutter ( 5526): <asynchronous suspension>
```

**Review by Rajala1404 — CHANGES_REQUESTED** [review]
Beside the thing with openFile() there is nothing else to add and i currently have also no time now to rewrite any dependencies (beside maybe file_picker and open_file but these are in there own PR)

**Comment by alessioC42** [comment]
You may have to clean the app cache before testing, because the previous code broke the file location.

**Review by Rajala1404 — APPROVED** [review]
Couldn't find anything that doesn't work that is specific to this branch

**Review by kurwjan — APPROVED** [review]

**Pull request merged**
