### PR TITLE
calendar: add search and data class + cleanup

### PR DESCRIPTION
**Pull request by alessioC42**
Implementing on device search for the calendar. (network search is scuffed, only returns specific results)
Also: allowing classic timetable view alongside Day view.

### CODE REVIEW

**Comment by Rajala1404** [comment]
Looks good at first look but if there are no results for the search you need to press the down Button on the Keyboard 2 times to get back to the normal view or if i exit the keyboard early and click again into nothing to get hide the list i come back to the keyboard vie without the list and need to press the button again

https://github.com/user-attachments/assets/0b3ee56e-e46d-40a3-9e75-f780d32926b3

**Review by Rajala1404 — CHANGES_REQUESTED** [review]
Looks good at first look but if there are no results for the search you need to press the down Button on the Keyboard 2 times to get back to the normal view or if i exit the keyboard early and click again into nothing to get hide the list i come back to the keyboard vie without the list and need to press the button again

https://github.com/user-attachments/assets/325cd924-0fe4-4408-8359-71f7683798fb

**Review by Rajala1404 — CHANGES_REQUESTED** [review]
Its still the same issue

**Review by Rajala1404 — CHANGES_REQUESTED** [review]
Ah ok but even with your new commit the behaivor of the down button is still broken, the Done button works fine so if i press the done button and the window ist still open i can just press somwhere else and it gets closed but if i use the down/back button of my keyboard sometime it closes the view but not the keyboard and other times it closes just the keyboard but the view stays open and if i click somwhere else the keyboard reopens and i need to press again to make it go (same with the actual back button/gesture)

**Comment by alessioC42** [comment]
Will look into that this evening. My tests suggested the system navigation to work flawless now. I am a bit confused, that your keyboard has an independent back button.

**Comment by Rajala1404** [comment]
> I am a bit confused, that your keyboard has an independent back button.
I tested it with the actual back button gesture and it shows the same behavior so i guess its actually the same button and its an issue with the back button

**Review by kurwjan — CHANGES_REQUESTED** [review]
[Screencast_20241007_171248.webm](https://github.com/user-attachments/assets/8ddc5c0f-cdc4-42a0-ba11-d3c5464cbc68)
That's funny and the keyboard also behaves strangely sometimes in other cases but I can't catch them on video.

[Screencast_20241007_171635.webm](https://github.com/user-attachments/assets/2a4cf27b-f94e-4b0d-a296-58b5955dc94a)
Also the next day in the timetable doesn't have any additional data.

image
image
Sorting by distance isn't really working? (If think you're trying to do it by what I've seen in the code). First comes 2025 then 2024 and later 2025 again. Then in 2025 February comes first, then May and etc. Maybe it only a problem at my school and not yours.

The rest should be good.

**Comment by kurwjan** [comment]
image
I think we can't really do anything about it.

**Comment by alessioC42** [comment]
Okay, I have tried everything I could think of. Using a PopScope, Focusnode, delayed, custom display layouts, etc. all did not work. Since I experience this behavior quite often on phones I am fine with it being merged as it is. Still is a big improvement. 
If you want to waste hours trying to enable this (without a race condition) good luck.

**Review by Rajala1404 — DISMISSED** [review]
Abgeshen von dem ding mit der Tastatur hab ich keine beschwerden also approved

**Comment by kurwjan** [comment]
Ich glaube ich hab da was gefunden. Kann man schon mal in #253 in `shared/keyboard_observer.dart` sehen und löst glaube auch das Problem hier.

**Review by Rajala1404 — COMMENTED** [review]
Can confirm that fixed it

**Comment by kurwjan** [comment]
Ist ready, außer das mein Montag aufeinmal am Sonntag beim Stundenplan ist.

**Pull request merged**
