### PR TITLE
Use native_dio_adapter

### PR DESCRIPTION
**Pull request by kurwjan**
There's also a Dio instance in `CustomConnectionChecker` but I don't think we need the adapter here.
[The iOS instance is also configurable](https://pub.dev/documentation/cupertino_http/latest/cupertino_http/URLSessionConfiguration-class.html) but I think the standard config is enough.
I hope I removed everything from our proxy implementation.

### Using embedded Cronet
```sh
$ flutter run/build --dart-define=cronetHttpNoPlay=true
```

### CODE REVIEW

**Comment by kurwjan** [comment]
Support for proxies on iOS and push notifications should be tested.
Push notifications should work, atleast they worked when I tested it.

**Review by alessioC42 — CHANGES_REQUESTED** [review]
> There's also a Dio instance in `CustomConnectionChecker` but I don't think we need the adapter here.

Why wouldn't we need it there? I do not think we should check for the connection any different than we do our requests.

**Comment by kurwjan** [comment]
> > There's also a Dio instance in `CustomConnectionChecker` but I don't think we need the adapter here.
> 
> Why wouldn't we need it there? I do not think we should check for the connection any different than we do our requests.

Added it. I thought because it just makes a tiny request to the same URL it doesn't need a NativeAdapter.

**Review by Rajala1404 — APPROVED** [review]
Fixed my complaints. So approved

**Review by alessioC42 — APPROVED** [review]

**Pull request merged**
